In [143]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [144]:
df = sns.load_dataset("iris")

In [145]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [146]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [147]:
from sklearn.model_selection import train_test_split

In [148]:

X = df.drop('species',axis = 1)
y = df['species']

In [149]:

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [150]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=13)

In [151]:

model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [152]:

model_knn.score(X_test,y_test)

1.0

In [153]:
from sklearn.svm import SVC

model_svm = SVC(gamma= 'auto')
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [154]:
model_svm.score(X_test,y_test)

1.0


# now lets use the grid search CV

In [155]:

from sklearn.model_selection import GridSearchCV

In [156]:
param_grid = {
    'C': [1, 10, 20,30],
    'kernel': ['rbf','linear'],
    'gamma': ['scale', 'auto']
}

In [157]:
grid = GridSearchCV(
    estimator=model_svm,
    param_grid=param_grid,
    scoring='accuracy',
    cv=5,
    verbose=2,
    n_jobs=-1
)

In [158]:
grid.fit(X,y)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(cv=5, estimator=SVC(gamma='auto'), n_jobs=-1,
             param_grid={'C': [1, 10, 20, 30], 'gamma': ['scale', 'auto'],
                         'kernel': ['rbf', 'linear']},
             scoring='accuracy', verbose=2)

In [159]:
grid.cv_results_

{'mean_fit_time': array([0.00827804, 0.00875864, 0.010567  , 0.01946316, 0.01335692,
        0.0150672 , 0.01308942, 0.01406898, 0.01369691, 0.01587005,
        0.01019554, 0.00948982, 0.01196666, 0.01092968, 0.00950317,
        0.01066403]),
 'std_fit_time': array([0.00095088, 0.00366569, 0.00410208, 0.01033606, 0.00561868,
        0.00567057, 0.00445358, 0.00322333, 0.00525109, 0.0035997 ,
        0.00171601, 0.00108728, 0.00365375, 0.00064457, 0.00268554,
        0.00175109]),
 'mean_score_time': array([0.00591664, 0.00842147, 0.01054726, 0.011274  , 0.01087165,
        0.01495843, 0.01276393, 0.00834732, 0.01044984, 0.01131425,
        0.01288409, 0.00883031, 0.00748353, 0.00818334, 0.01101761,
        0.00994067]),
 'std_score_time': array([0.00056945, 0.00188785, 0.00669479, 0.00577119, 0.00385114,
        0.00278873, 0.00492765, 0.00425186, 0.00184819, 0.00541362,
        0.00524726, 0.00253003, 0.00159105, 0.00308618, 0.00314031,
        0.00196503]),
 'param_C': masked_array(data=[1, 1, 1, 1, 10, 10, 10, 10, 20, 20, 20, 20, 30, 30, 30,
                    30],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_gamma': masked_array(data=['scale', 'scale', 'auto', 'auto', 'scale', 'scale',
                    'auto', 'auto', 'scale', 'scale', 'auto', 'auto',
                    'scale', 'scale', 'auto', 'auto'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        1.        , 0.96666667, 1.        , 0.96666667, 1.        ,
        0.96666667, 1.        , 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([0.96666667, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.9       , 0.96666667, 0.9       , 0.96666667, 0.9       ,
        0.9       , 0.9       , 0.93333333, 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.93333333, 0.96666667, 0.9       , 0.93333333,
        0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.98      , 0.98      , 0.98      , 0.98      ,
        0.97333333, 0.98      , 0.97333333, 0.98      , 0.96666667,
        0.96666667, 0.96666667, 0.97333333, 0.96      , 0.96      ,
        0.96      ]),
 'std_test_score': array([0.02108185, 0.01632993, 0.01632993, 0.01632993, 0.01632993,
        0.03887301, 0.01632993, 0.03887301, 0.01632993, 0.0421637 ,
        0.03651484, 0.0421637 , 0.02494438, 0.04898979, 0.03887301,
        0.04898979]),
 'rank_test_score': array([11,  1,  1,  1,  1,  7,  1,  7,  1, 11, 10, 11,  7, 14, 14, 14],
       dtype=int32)}

In [160]:

results = pd.DataFrame(grid.cv_results_)

In [161]:
results

    mean_fit_time  std_fit_time  mean_score_time  ...  mean_test_score  std_test_score rank_test_score
0        0.008278      0.000951         0.005917  ...         0.966667        0.021082              11
1        0.008759      0.003666         0.008421  ...         0.980000        0.016330               1
2        0.010567      0.004102         0.010547  ...         0.980000        0.016330               1
3        0.019463      0.010336         0.011274  ...         0.980000        0.016330               1
4        0.013357      0.005619         0.010872  ...         0.980000        0.016330               1
5        0.015067      0.005671         0.014958  ...         0.973333        0.038873               7
6        0.013089      0.004454         0.012764  ...         0.980000        0.016330               1
7        0.014069      0.003223         0.008347  ...         0.973333        0.038873               7
8        0.013697      0.005251         0.010450  ...         0.980000        0.016330               1
9        0.015870      0.003600         0.011314  ...         0.966667        0.042164              11
10       0.010196      0.001716         0.012884  ...         0.966667        0.036515              10
11       0.009490      0.001087         0.008830  ...         0.966667        0.042164              11
12       0.011967      0.003654         0.007484  ...         0.973333        0.024944               7
13       0.010930      0.000645         0.008183  ...         0.960000        0.048990              14
14       0.009503      0.002686         0.011018  ...         0.960000        0.038873              14
15       0.010664      0.001751         0.009941  ...         0.960000        0.048990              14

[16 rows x 16 columns]

In [162]:

results[['param_C','param_kernel','mean_test_score' , 'rank_test_score']]

    param_C param_kernel  mean_test_score  rank_test_score
0         1          rbf         0.966667               11
1         1       linear         0.980000                1
2         1          rbf         0.980000                1
3         1       linear         0.980000                1
4        10          rbf         0.980000                1
5        10       linear         0.973333                7
6        10          rbf         0.980000                1
7        10       linear         0.973333                7
8        20          rbf         0.980000                1
9        20       linear         0.966667               11
10       20          rbf         0.966667               10
11       20       linear         0.966667               11
12       30          rbf         0.973333                7
13       30       linear         0.960000               14
14       30          rbf         0.960000               14
15       30       linear         0.960000               14

In [163]:
from sklearn.model_selection import RandomizedSearchCV

In [164]:
param_dist = {
    'C': [1,10,20,30],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

In [165]:
random_search = RandomizedSearchCV(
    estimator= model_svm,
    param_distributions=param_dist,
    n_iter=4,
    scoring='accuracy',
    cv=5,
    verbose=2,
    n_jobs=-1,
    random_state=42,
    return_train_score= False
)

In [166]:
random_search.fit(X,y)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4, n_jobs=-1,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['linear', 'rbf']},
                   random_state=42, scoring='accuracy', verbose=2)

In [167]:
results = pd.DataFrame(random_search.cv_results_)

In [168]:

results[['param_C','param_kernel','mean_test_score' , 'rank_test_score']]

   param_C param_kernel  mean_test_score  rank_test_score
0        1       linear         0.980000                1
1        1          rbf         0.966667                3
2       10          rbf         0.980000                1
3       30       linear         0.960000                4