In [42]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [43]:
df = sns.load_dataset("iris")

In [44]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [45]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [46]:
from sklearn.model_selection import train_test_split

In [47]:

X = df.drop('species',axis = 1)
y = df['species']

In [48]:

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [49]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=13)

In [50]:

model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [51]:

model_knn.score(X_test,y_test)

1.0

In [52]:
from sklearn.svm import SVC

model_svm = SVC(gamma= 'auto')
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [53]:
model_svm.score(X_test,y_test)

1.0


# now lets use the grid search CV

In [54]:

from sklearn.model_selection import GridSearchCV

In [55]:
param_grid = {
    'C': [1, 10, 20,30],
    'kernel': ['rbf','linear'],
    'gamma': ['scale', 'auto']
}

In [56]:
grid = GridSearchCV(
    estimator=model_svm,
    param_grid=param_grid,
    scoring='accuracy',
    cv=5,
    verbose=2,
    n_jobs=-1
)

In [57]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(cv=5, estimator=SVC(gamma='auto'), n_jobs=-1,
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']},
             verbose=2)

In [58]:
grid.cv_results_

{'mean_fit_time': array([0.00869098, 0.0093472 , 0.00958457, 0.01125998, 0.01217051,
        0.01163254, 0.01552286, 0.0114924 ]),
 'std_fit_time': array([0.0005357 , 0.00197967, 0.00121253, 0.00257288, 0.0021741 ,
        0.00439944, 0.00621128, 0.00310699]),
 'mean_score_time': array([0.00597348, 0.00831299, 0.0143075 , 0.00880041, 0.01120248,
        0.00923524, 0.01038141, 0.00864539]),
 'std_score_time': array([0.00073676, 0.0046406 , 0.00617957, 0.00421957, 0.00852508,
        0.00363637, 0.00259942, 0.00204674]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.95, 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.8 , 0.85, 0.8 , 0.85, 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'split4_test_score': array([0.95, 0.95, 1.  , 0.95, 0.95, 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.94, 0.95, 0.93, 0.93, 0.92, 0.93, 0.93, 0.94]),
 'std_test_score': array([0.03741657, 0.04472136, 0.07483315, 0.0509902 , 0.0678233 ,
        0.0509902 , 0.07483315, 0.05830952]),
 'rank_test_score': array([2, 1, 4, 6, 8, 6, 4, 3], dtype=int32)}

In [59]:

results = pd.DataFrame(grid.cv_results_)

In [60]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008691,0.000536,0.005973,0.000737,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,2
1,0.009347,0.001980,0.008313,0.004641,1,linear,"{'C': 1, 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
2,0.009585,0.001213,0.014307,0.006180,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
3,0.011260,0.002573,0.008800,0.004220,10,linear,"{'C': 10, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,6
4,0.012171,0.002174,0.011202,0.008525,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,8
5,0.011633,0.004399,0.009235,0.003636,20,linear,"{'C': 20, 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,6
6,0.015523,0.006211,0.010381,0.002599,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
7,0.011492,0.003107,0.008645,0.002047,30,linear,"{'C': 30, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,3

In [63]:

results[['param_C','param_kernel','mean_test_score' , 'rank_test_score']]

   param_C param_kernel  mean_test_score  rank_test_score
0        1          rbf             0.94                2
1        1       linear             0.95                1
2       10          rbf             0.93                4
3       10       linear             0.93                6
4       20          rbf             0.92                8
5       20       linear             0.93                6
6       30          rbf             0.93                4
7       30       linear             0.94                3